### ISSUE TITLE
Issues with Node v0.12.0

### ISSUE THREAD

**Issue by acerdas84** [winstonjs/winston-syslog#39]
I am having the following error after upgrading to node v0.12.0

/usr/local/bin/node web/server.js
/mypath/node_modules/winston-syslog/node_modules/unix-dgram/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/mypath/node_modules/winston-syslog/node_modules/unix-dgram/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/mypath/node_modules/winston-syslog/node_modules/unix-dgram/lib/unix_dgram.js:4:34)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)

Process finished with exit code 1

**Comment by santigimeno** [comment]
@acerdas84 I can't reproduce this issue with `1.0.0` nor `master`. Can you post a simple test case that reproduces this issue?

**Comment by acerdas84** [comment]
By just doing this I get the error    
     
    'use strict';
    var
        winston = require('winston');

    // Requiring winston-syslog will expose
    // winston.transports.Syslog
    require('winston-syslog').Syslog;

*/usr/local/bin/node testing.js
/path/packsize/node_modules/winston-syslog/node_modules/unix-dgram/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/path/packsize/node_modules/winston-syslog/node_modules/unix-dgram/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/path/packsize/node_modules/winston-syslog/node_modules/unix-dgram/lib/unix_dgram.js:4:34)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)*

Am I doing something wrong? This works for me in node v0.10.25 but when I did that on v0.12.0 I started getting that error

Regards

**Comment by santigimeno** [comment]
@acerdas84 it works for me. Have you rebuilt the module after switching to 0.12.0 with `npm rebuild` ?

**Comment by acerdas84** [comment]
Oh that worked, thanks sorry for the trouble

**Comment by wintermuted** [comment]
Switching to 0.12 and rebuilding worked for me when I encountered this issue. :+1:
