### ISSUE TITLE
Unix socket throws error when buffer is full

### ISSUE THREAD

**Issue by thesmart** [winstonjs/winston-syslog#84]
When `winston-syslog` attempts to write to a unix socket, if buffer is full, the socket operation will block.  When the socket is in non-blocking mode, this results in the socket write operation throwing a `EAGAIN` error:

```
Error: send -11
    at errnoException (node_modules/unix-dgram/lib/unix_dgram.js:18:11)
    at Socket.send (node_modules/unix-dgram/lib/unix_dgram.js:93:24)
    at node_modules/winston-syslog/lib/winston-syslog.js:191:21
    at Syslog.connect (node_modules/winston-syslog/lib/winston-syslog.js:253:9)
    at Syslog.log (node_modules/winston-syslog/lib/winston-syslog.js:157:8)
    at transportLog (node_modules/winston/lib/winston/logger.js:228:15)
    at node_modules/async/lib/async.js:157:13
    at _each (node_modules/async/lib/async.js:57:9)
    at Object.async.each (node_modules/async/lib/async.js:156:9)
    at Logger.log (node_modules/winston/lib/winston/logger.js:240:9)
```

The culprit is line `winston-syslog.js:191`:
```js
    //
    // Write to the `tcp*`, `udp*`, or `unix` socket.
    //
    if (self.isDgram) {
      buffer = new Buffer(syslogMsg);

      if (self.protocolType === 'udp') {
        self.inFlight++;
        self.socket.send(buffer, 0, buffer.length, self.port, self.host, onError);
      }
      else if (self.protocol === 'unix') {
        self.socket.send(buffer, 0, buffer.length, self.path, onError);
      }
```

That line should probably be wrapped in a try/catch block:
```
When the message does not fit into the send buffer of the socket, send normally blocks, unless the socket has been placed in non-blocking I/O mode. In non-blocking mode it would return EAGAIN in this case. The select(2) call may be used to determine when it is possible to send more data.
```

**Comment by santigimeno** [comment]
@thesmart have you tried using `unix-connect` as a transport? I think it should not have that error. It uses *connected* unix datagram sockets and can detect that scenario and enqueue the messages until the socket is ready again (the buffer is not full anymore)

**Comment by thesmart** [comment]
Oh cool! Thanks.
