### ISSUE TITLE
Errors when closing logger with syslog transport

### ISSUE THREAD

**Issue by bbusschots-mu** [winstonjs/winston-syslog#85]
When I call `.close()` on a logger with a syslog transport the following error is thrown:

```
failed to close logger TypeError: self.socket.close is not a function
    at _close (/Users/bart/Documents/Temp/fromMUGit/moodle-integration-33/node_modules/winston-syslog/lib/winston-syslog.js:227:21)
    at exports.Syslog.Syslog.close (/Users/bart/Documents/Temp/fromMUGit/moodle-integration-33/node_modules/winston-syslog/lib/winston-syslog.js:236:4)
    at /Users/bart/Documents/Temp/fromMUGit/moodle-integration-33/node_modules/winston/lib/winston/logger.js:405:17
    at Array.forEach (native)
    at exports.Logger.Logger.close (/Users/bart/Documents/Temp/fromMUGit/moodle-integration-33/node_modules/winston/lib/winston/logger.js:402:15)
...
```

**Comment by yuvipanda** [comment]
I get this too, preventing use of tcp for logging:

```
/home/yuvipanda/code/jupyterhub-loadtest/node_modules/winston-syslog/lib/winston-syslog.js:201
          this.socket.close();
                      ^

TypeError: this.socket.close is not a function
    at Timeout._close [as _onTimeout] (/home/yuvipanda/code/jupyterhub-loadtest/node_modules/winston-syslog/lib/winston-syslog.js:201:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
```
