### ISSUE TITLE
Error trying to use 2.0.0 

### ISSUE THREAD

**Issue by davidchappelle** [winstonjs/winston-syslog#92]
I get the following error trying to use 2.0.0 with the README.md instructions. Either the instructions need to be updated or there is a syntax error in the new release:

```
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/share/deathstar/node/modules/logger.js:4:16)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

Error is happening as a result of the require:

```
  1 'use strict';
  2 
  3 const winston = require('winston');
  4 require('winston-syslog').Syslog;
  5 
```

**Comment by chriskerley78910** [comment]
Have the bug here too.

**Comment by NeonWizard** [comment]
Same here.

**Comment by SpenRue** [comment]
Do you guys happen to be running an older version of node?

Anything earlier than v6 is not supported apparently.

I was getting the same error trying to use this with node v4 which doesn't support object destructuring, which is being used in winstonjs.
